import style from './style';
import './useActive';
import './useFlex';
import './useHover';
import './useMedia';
import './useMobile';
import './usePc';
import './useScrollBlock';
export { IStyle, IProps } from './interface';
export default style;
